# Generated by Django 6.1 on 2026-10-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_alter_applicant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
