# Generated by Django 6.1 on 2026-08-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='uploaded_at',
        ),
    ]
