# Generated by Django 6.1 on 2026-08-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_resume_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='original_filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
