# Generated by Django 6.1 on 2026-08-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_resume_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('PE', 'PENDING'), ('PR', 'PROCESSING'), ('D', 'DONE'), ('F', 'FAILED')], default='PE', max_length=2),
        ),
    ]
