# Generated by Django 6.1 on 2026-08-26 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_resume_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('chunk_index', models.PositiveIntegerField(help_text='Order index of the chunk within the resume')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='jobs.resume')),
            ],
            options={
                'ordering': ['chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('resume', 'chunk_index'), name='unique_resume_chunk_index')],
            },
        ),
    ]
