# jobs/migrations/0007_convert_field_types.py
# Generated by Django 6.1 on 2026-08-27 11:09

from django.db import migrations


def copy_json_to_vector(apps, schema_editor):
    ResumeChunk = apps.get_model("jobs", "ResumeChunk")

    # Using iterator() to handle large datasets efficiently
    for chunk in ResumeChunk.objects.all().iterator():
        if chunk.embedding:
            # Assign the JSON list directly to the VectorField
            chunk.embedding_fr = chunk.embedding
            chunk.save(update_fields=["embedding_fr"])


def copy_vector_to_json(apps, schema_editor):
    ResumeChunk = apps.get_model("jobs", "ResumeChunk")
    for chunk in ResumeChunk.objects.all().iterator():
        if chunk.embedding_fr:
            # Revert vector back to a standard Python list for the JSONField
            chunk.embedding = list(chunk.embedding_fr)
            chunk.save(update_fields=["embedding"])


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_resumechunk_embedding_fr"),
    ]

    operations = [
        migrations.RunPython(copy_json_to_vector, reverse_code=copy_vector_to_json),
    ]
