# Generated by Django 6.1 on 2026-08-27 11:20

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_convert_field_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resumechunk",
            name="embedding",
        ),
        migrations.AlterField(
            model_name="resumechunk",
            name="embedding_fr",
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
    ]
