# Generated by Django 6.1 on 2026-08-27 12:07

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_remove_resumechunk_embedding_fr_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="resumechunk",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding_fr"],
                m=16,
                name="resume_chunk_embedding_hnsw_idx",
                opclasses=["vector_l2_ops"],
            ),
        ),
    ]
