# Generated by Django 6.1 on 2026-08-27 12:15

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_resumechunk_resume_chunk_embedding_hnsw_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resumechunk',
            name='resume_chunk_embedding_hnsw_idx',
        ),
        migrations.RenameField(
            model_name='resumechunk',
            old_name='embedding_fr',
            new_name='embedding',
        ),
        migrations.AddIndex(
            model_name='resumechunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='resume_chunk_embedding_hnsw_idx', opclasses=['vector_l2_ops']),
        ),
    ]
