# Generated by Django 6.1 on 2026-08-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_resumechunk_resume_chunk_embedding_hnsw_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='head_count',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
