# Generated by Django 6.1 on 2026-08-27 13:03

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_head_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
