# Generated by Django 6.1 on 2026-08-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='retrieval_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='ranking_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('computing', 'Computing'), ('retrieval_done', 'Retrieval Done'), ('done', 'Done'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
