# Generated by Django 6.1 on 2026-08-28 12:53

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_application_retrieval_score_job_ranking_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resumechunk',
            name='resume_chunk_embedding_hnsw_idx',
        ),
        migrations.AddIndex(
            model_name='resumechunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='resume_chunk_embedding_hnsw_idx', opclasses=['vector_ip_ops']),
        ),
    ]
