# Generated by Django 6.1 on 2026-08-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_remove_resumechunk_resume_chunk_embedding_hnsw_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='full_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
