# Generated by Django 6.1 on 2026-08-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_resume_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
