# Generated by Django 6.1 on 2026-08-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_resume_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
