# Generated by Django 6.1 on 2026-08-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_alter_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='head_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
