# Generated by Django 6.1 on 2026-08-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_alter_job_head_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='llm_profile',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
