# Generated by Django 6.1 on 2026-10-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_application_applicant_application_guest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
