# Generated by Django 6.1 on 2026-10-01 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_alter_applicant_id'),
        ('jobs', '0024_resume_resume_exactly_one_of_company_or_applicant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resume',
            name='resume_exactly_one_of_company_or_applicant',
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applicant__isnull', True), ('company__isnull', False)), models.Q(('applicant__isnull', False), ('company__isnull', True)), models.Q(('applicant__isnull', True), ('company__isnull', True)), _connector='OR'), name='resume_exactly_one_of_company_or_applicant'),
        ),
    ]
