# Generated by Django 6.1 on 2026-10-03 19:55

import pgvector.django.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_remove_resume_resume_exactly_one_of_company_or_applicant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='job_embedding_hnsw_idx', opclasses=['vector_ip_ops']),
        ),
    ]
